### PR TITLE
Exit after all processes being handled

### LINKED ISSUE #3: Exit after all processes being handled?
Is there a reason for not exiting the listener after all processes have been handled? This could be done by changing the while condition in `_listen()` from `1` to `not self.startup_done`.

### PR DESCRIPTION
**Pull request by dontub**
Fix #3.

### CODE REVIEW

**Comment by bendikro** [comment]
Did you run the tests?

**Comment by dontub** [comment]
The tests should now run as before. For me 8 tests in `test_dependent_startup_events.py` fail with this error (with and without my change):
```
line = '<supervisor.events.ProcessStateRunningEvent instance at 0x7ffa92da16c8>'

    def get_headers(line):
>       return dict([ x.split(':') for x in line.split() ])
E       ValueError: dictionary update sequence element #0 has length 1; 2 is required

.eggs/supervisor-4.0.2-py2.7.egg/supervisor/childutils.py:24: ValueError
```

And to the tests in `test_dependent_startup.py`: I think in all tests the started and running processes should be asserted. Is there any actual difference between `test_run_ping_example_running` and `test_run_ping_example_immedate_exit`? The only difference I spotted are the commands of the services which are irrelevant for the test.

**Comment by bendikro** [comment]
Thanks. Your change has been merged.

The tests were failing when run with supervisor v4. I've pushed a fix for that.

> And to the tests in `test_dependent_startup.py`: I think in all tests the started and running processes should be asserted.

Feel free to make another PR :-)

Is there any actual difference between `test_run_ping_example_running` and `test_run_ping_example_immedate_exit`? The only difference I spotted are the commands of the services which are irrelevant for the test.

Yeah, the only difference is `-c 1` vs `-c 2`. So the ping commands in `test_run_ping_example_running` will send two ping packets, and will exit after 1 second, while the commands in `test_run_ping_example_immedate_exit` exit immediately after the first ping.

**Comment by dontub** [comment]
The tests run without failure now.

As far as I can see, the commands are never executed so it makes no difference whether it is `-c 1` or `-c 2` or cmd is just `foo`.

**Comment by bendikro** [comment]
You are correct, the commands are not run in the tests. I used those tests to create the supervisor ini files for [example.md](https://github.com/bendikro/supervisord-dependent-startup/blob/master/example.md), and then run in manually to get the output.

**Pull request closed without merging**
